param(
  [string]$StackName = 'leaveservice',
  [string]$AuthBase = 'http://10.0.2.2:8081'
)

Write-Host "Looking up ApiUrl for CloudFormation stack: $StackName";
$apiUrl = aws cloudformation describe-stacks --stack-name $StackName --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" --output text 2>$null

if (!$apiUrl -or $apiUrl -eq 'None') {
  Write-Error "Could not find ApiUrl output for stack '$StackName'. Make sure the stack is deployed and the 'ApiUrl' Output exists.";
  exit 1;
}

Write-Host "Using ApiUrl: $apiUrl";

# Also write a small Dart file with the generated ApiUrl so it can be
# consumed by the app at runtime if needed.
$outFile = Join-Path -Path "..\lib\config" -ChildPath "api_gateway.dart"
$content = @"
// Generated by run_with_api_gateway.ps1
const String generatedApiGatewayUrl = '$apiUrl';
"@

Write-Host "Writing generated config to: $outFile";
Set-Content -Path $outFile -Value $content -Encoding UTF8

# Compose flutter run with dart-define flags
$envArgs = "--dart-define=AUTH_BASE_URL=$AuthBase --dart-define=API_GATEWAY_URL=$apiUrl --dart-define=FORCE_API_GATEWAY=true"

Write-Host "Running flutter with: $envArgs";
flutter run $envArgs
